server:
  port: 8086
feign:
  okhttp:
    enabled: true # 开启OKHttp连接池支持
  sentinel:
    enabled: true # 开启Feign对Sentinel的整合
hm:
  swagger:
    title: 交易服务接口文档
    package: com.hmall.pay.controller
  db:
    database: hm-pay

spring:
  rabbitmq:
    host: 192.168.50.128 # 你的虚拟机IP
    port: 5672 # 端口
    virtual-host: /hmall # 虚拟主机
    username: ShiHaoHu # 用户名
    password: 123 # 密码
    listener:
      simple:
        prefetch: 1